### ISSUE TITLE
veryfiFiles.py crashes

### ISSUE THREAD

**Issue by glatard** [big-data-lab-team/repro-tools#3]
$ ./verifyFiles.py test.txt 
Traceback (most recent call last):
  File "./verifyFiles.py", line 195, in <module>
    main()
  File "./verifyFiles.py", line 184, in main
    study_folder_details_dict_list=populate_study_folder_dict(file_with_conditions_list)
  File "./verifyFiles.py", line 57, in populate_study_folder_dict
    temp_study_folder_dict[folder]=get_dict_with_file_and_dir_attributes(folder_path)
NameError: global name 'folder_path' is not defined

**Comment by lalet** [comment]
Fixed. Please re-test.
